---
name: rack
version: '2.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: ec140aff951e3af39846eed4525ba5d040d294fa
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
